version: '2'
services:
  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - '.:/app:ro'
    links:
      - raise
    depends_on:
      - raise
  couchbase:
    image: couchbase/server
    restart: always
    volumes:
      - './couchbase:/opt/couchbase/var:rw'
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  raise:
    restart: always
    volumes:
      - '.:/app:rw'
      - '/app/vendor'
    entrypoint: ['docker-php-entrypoint']
    expose:
      - 9000
    build:
      context: .
      dockerfile: Dockerfile
    command: 'bash /app/raise-init.sh'
    depends_on:
      - couchbase
    links:
      - couchbase
